services:
  beat-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_YOUTUBE_API_TOKEN: ${VITE_YOUTUBE_API_TOKEN}
    ports:
      - "3000:3000"
    restart: unless-stopped
